version: "3.5"
services:
  app:
    image: igor875126/sshuttle
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sshuttle
    #restart: unless-stopped
    environment:
      # Read documentation to get more at: https://sshuttle.readthedocs.io/en/stable/usage.html
      - SSHUTTLE_ARGS=-x 192.168.0.0/16 --dns -r root@206.189.154.79:3785 0/0
    volumes:
      - ./ssh-key/id_rsa:/root/.ssh/id_rsa:ro
      - ./ssh-key/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
    network_mode: host
    cap_add:
      - NET_ADMIN
