version: "3.5"
services:
  app:
    image: igor875126/sshuttle
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sshuttle
    restart: unless-stopped
    # Read documentation to get more at: https://sshuttle.readthedocs.io/en/stable/usage.html
    environment:
      # Use to create reverese tunnels (multiple if you want)
      # 2222 will be opened on you JUMP SERVER 50022 will be forwarded to 2222
      - SSH_ARGS=ssh -R 2222:localhost:50022 -R 8000:localhost:6556
      - SSHUTTLE_ARGS=--disable-ipv6 -x 192.0.0.0/8 -x 172.0.0.0/8 --dns -r root@JUMPSERVERIP:JUMPSERVERPORT 0/0
    volumes:
      - ./ssh-key/id_rsa:/root/.ssh/id_rsa:ro
      - ./ssh-key/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
    network_mode: host
    cap_add:
      - NET_ADMIN
